Add WORKBENCH_TAG

diff --git a/renv-checks/action.yaml b/renv-checks/action.yaml
--- a/renv-checks/action.yaml
+++ b/renv-checks/action.yaml
@@ -83,7 +83,7 @@ runs:
     - name: Configure AWS credentials via OIDC
       id: aws-creds
       if: ${{ steps.validate-org-workflow.outputs.is_valid == 'true' }}
-      uses: aws-actions/configure-aws-credentials@v4.1.0
+      uses: aws-actions/configure-aws-credentials@v5.0.0
       with:
         role-to-assume: ${{ inputs.role-to-assume }}
         aws-region: ${{ inputs.aws-region }}
@@ -103,3 +103,10 @@ runs:
           /home/rstudio/lesson/renv
           /usr/local/lib/R/site-library
         key: ${{ github.repository }}-${{ steps.wb-vers.outputs.container-version }}-renv-${{ steps.set-renv-hash.outputs.renv-cache-hashsum }}
+
+    - name: Fail on renv cache miss
+      if: steps.check-renv.outputs.renv-needed == 'true' && steps.check-renv.outputs.renv-cache-available != 'true'
+      run: |
+        echo "❌ renv cache required but none available. Please run the "02 Maintain: Check for Updated Packages" then the "03 Maintain: Apply Package Cache" workflows."
+        exit 1
+      shell: bash
