update sysdeps discovery to have a backup (#42)

diff --git a/setup-sandpaper/action.yaml b/setup-sandpaper/action.yaml
--- a/setup-sandpaper/action.yaml
+++ b/setup-sandpaper/action.yaml
@@ -43,10 +43,26 @@ runs:
         id: run-apt
         shell: bash
         run: |
-          sudo apt-get install -y \
-           libxslt-dev \
-           $(curl https://carpentries.r-universe.dev/stats/sysdeps 2> /dev/null | jq -r '.headers[0] | select(. != null)') 2> /dev/null \
-          || echo "Not on Ubuntu"
+          sudo apt update
+          curl https://carpentries.r-universe.dev/stats/sysdeps 2> /dev/null \
+          | jq -r '.headers[0] | select(. != null)' 2> /dev/null \
+          > ${{ runner.temp }}/sysdeps.txt
+          if [[ `wc -l < ${{ runner.temp }}/sysdeps.txt` -gt 0 ]]; then
+            echo 'sysdeps acquired'
+          else
+            echo 'fetching sysdeps from descriptions'
+            curl https://carpentries.r-universe.dev/stats/descriptions \
+            | jq -r '._builder.sysdeps | .[].headers | select(. != null)' 2> /dev/null \
+            > ${{ runner.temp }}/sysdeps.txt
+          fi
+          if [[ `wc -l < ${{ runner.temp }}/sysdeps.txt` -eq 0 ]]; then
+            echo "::warn::System dependencies could not be acquired. Builds may fail"
+            exit 1
+          else
+            echo "found sysdeps: $(cat ${{ runner.temp }}/sysdeps.txt)"
+          fi
+          printf "libxslt-dev\n" >> ${{ runner.temp }}/sysdeps.txt
+          sudo xargs apt-get install --fix-missing -y < ${{ runner.temp }}/sysdeps.txt || echo "Not on Ubuntu"
 
       - name: Restore R package cache
         uses: actions/cache@v2
